spring:
  main:
    banner-mode: "off"

blog-database:
  host: ${BLOG_DATABASE_HOST:localhost}
  port: ${BLOG_DATABASE_PORT:5432}
  name: ${BLOG_DATABASE_NAME:app}
  user: ${BLOG_DATABASE_ROLE:app}
  password: ${BLOG_DATABASE_PASSWORD:insecure-app-user-password}
  enable-ssl: false
