spring:
  main:
    banner-mode: "off"

blog-database:
  host: ${BLOG_DATABASE_HOST:localhost}
  port: ${BLOG_DATABASE_PORT:5432}
  name: ${BLOG_DATABASE_NAME:fog-blog}
  user: ${BLOG_DATABASE_ROLE:${USER:fog-blog}}
  password: ${BLOG_DATABASE_PASSWORD:""}
  enable-ssl: false
